permalink:           /:title/
relative_permalinks: true

title:               Pavol Rusnak
tagline:             'hacker'
description:         'Pavol Rusnak'
url:                 http://gk2.sk
baseurl:             ''
paginate:            5

author:
  name:              Pavol Rusnak
  url:               https://twitter.com/pavolrusnak
  email:             stick@gk2.sk
