gems:
  - jekyll-paginate
  - jekyll-archives

permalink:           /:title/

title:               Pavol Rusnak
tagline:             'hacker'
description:         'Pavol Rusnak'
url:                 http://gk2.sk
baseurl:             ''
paginate:            5

author:
  name:              Pavol Rusnak
  url:               https://twitter.com/pavolrusnak
  email:             stick@gk2.sk

jekyll-archives:
  enabled:
  - year
  layout: 'archive'
  permalinks:
    year: '/archive/:year/'
